language: ruby
cache: 
  bundler: true
  directories:
    - /home/travis/.rvm/
rvm:
- 2.4.0

branches:
  only:
    - master

script:
  - ./_scripts/test.sh

addons:
  apt:
    packages:
    - libimage-exiftool-perl
    - ack-grep
