language: ruby
rvm:
- 2.2

branches:
  only:
    - master

script:
  - ./_scripts/test.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libimage-exiftool-perl
    - ack-grep
