title: Alex's Jazz Catalogue
description: >
  Alex Gondek's jazz collection and list of recommended books, movies and videos.
baseurl: ""
url: "http://jazz.gondek.ca"
alex_url: "http://alex.gondek.ca"
permalink: "/:title"
exclude: ['README.md', 'vendor', 'Gemfile', 'CNAME']
